orbs: # declare what orbs we are going to use
  node: circleci/node@2.0.2 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
              - v1-dependencies-{{ checksum "package-lock.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
      - run: npm install
      - run: npm install mocha-junit-reporter # just for CircleCI
      - save_cache:
          paths:
              - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: mkdir reports

      # Run mocha
      - run:
          name: npm test
          command: npm run test:ci
          when: always

      # Run eslint
      - run:
          name: eslint
          command: |
              ./node_modules/.bin/eslint ./ --format junit --output-file ./reports/eslint/eslint.xml
          when: always

      # Upload results
      - store_test_results:
          path: reports
      - store_artifacts:
          path: ./reports/mocha/test-results.xml
      - store_artifacts:
          path: ./reports/eslint/eslint.xml
      - store_artifacts: # upload test coverage as artifact
          path: ./coverage/lcov.info
          # prefix: tests

workflows:
  build:
    jobs:
      - build
  matrix-tests:
    jobs:
      - node/test:
          version: 16.5.0

